### ISSUE TITLE
problems parsing the SNS test message provided on Lambda

### ISSUE THREAD

**Issue by rterbush** [robbwagoner/aws-lambda-sns-to-slack#1]
Just grabbed your very nifty lambda script and in attempting to get things running, I hit the following snag when attempting to test using the SNS example message on Lambda. Local test message that you provide seems to work.

Debug message just before the json.loads on line 106 prints correctly. Line numbers will be slightly off from your version as I am in process of adding KMS encrypted URL support.

```
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      106,
      "lambda_handler",
      "json_msg = json.loads(sns['Message'])"
    ],
    [
      "/usr/lib64/python2.7/json/__init__.py",
      338,
      "loads",
      "return _default_decoder.decode(s)"
    ],
    [
      "/usr/lib64/python2.7/json/decoder.py",
      366,
      "decode",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"
    ],
    [
      "/usr/lib64/python2.7/json/decoder.py",
      384,
      "raw_decode",
      "raise ValueError(\"No JSON object could be decoded\")"
    ]
  ],
  "errorType": "ValueError",
  "errorMessage": "No JSON object could be decoded"
}
```

```
START RequestId: efb532d1-bf1b-11e5-a05d-1f0bb4c94980 Version: 4
DEBUG: Hello from SNS!
No JSON object could be decoded: ValueError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 106, in lambda_handler
    json_msg = json.loads(sns['Message'])
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

END RequestId: efb532d1-bf1b-11e5-a05d-1f0bb4c94980
REPORT RequestId: efb532d1-bf1b-11e5-a05d-1f0bb4c94980  Duration: 0.58 ms   Billed Duration: 100 ms     Memory Size: 128 MB Max Memory Used: 16 MB  
```

**Comment by rterbush** [comment]
Closing this as I realize the error is caused because the SNS test message provided by AWS is not a JSON formatted value for the Sns['Message'] field. Sorry for the noise. Will give you a PR when I sort this out.
